### ISSUE TITLE
Email message is rendered from template in one line

### ISSUE THREAD

**Issue by mikaelkundert** [Marak/node_mailer#32]
My email templates contains multiple lines but I receive the message in one line.

My message template is:

```
Hello {{name}}!
Start your session with your friends by going to following URL:

{{sessionUrl}}
```

But I receive my message as: 

```
Hello James! Start your session with your friends by going to following URL: http://theurl.com
```

Any ideas why this is happening? I tried to view the message from webmail and same thing happens there too.

I tried to check issues from nodemailer and mustache.js in case if someone has reported about the same problem but no results..

**Comment by bmeck** [comment]
Templates by default render to html emails, html spacing would contract those.

**Comment by mikaelkundert** [comment]
Okay, that is a positive surprise. Can I optionally set it to be in text format?

**Comment by bmeck** [comment]
not right now no. There are some issues due to templating being a
unique property and thus being multiplexed to associated with either
html or plaintext, right now we just defaulted to plaintext since all
modern email clients accept html. It was an API descision, but if a
decent api could be found to do both html and plaintext at the same
time, we might have cause to implement that.

**Comment by cmiller-r7** [comment]
@bmeck Do you know if there is a fix for the newline spacing issue? I am still experiencing it. I do realize this was a decade ago
